### ISSUE TITLE
Ask Galvanize about venue

### ISSUE THREAD

**Issue by switzersc** [codefordenver/codeacross-2016#21]
Cost and availability for 9-5 Saturday, March 5.

**Comment by wdoug** [comment]
From Krista:

> We would absolutely love having you guys on campus again! Prices have gone up a bit since last year for reserving the entire Atrium. It is typically $2,000 to reserve it for the day. Since you all use the space so much and it would be bringing in a an awesome group of people, I would be happy to give you a 50% discount. It would be $1,000 for the day - which includes the entire atrium, AV, Wifi, a stage, staffing and cleaning.
> 
> Let me know if you would like to do this and I will create a contract for you!

**Comment by switzersc** [comment]
LOL "prices have gone up a bit". Even with the "discount", isn't that 5 times what we paid last year?
