### ISSUE TITLE
Ask about Commons on Champa as venue

### ISSUE THREAD

**Issue by switzersc** [codefordenver/codeacross-2016#26]
cost and availability for 9-5, March 5.

**Comment by wdoug** [comment]
The event space is normally $500 for nonprofits, however, I have heard they may be willing to host us for free if it aligns with their mission and they can co-program.

> The downstairs floor accommodates up to 400, with 250 in our event space and 150 in the lounge.

**Comment by switzersc** [comment]
this is hands-down better than galvanize then, even if they cant give it to us for free.

**Comment by wdoug** [comment]
Yup
