### ISSUE TITLE
Recruit Participants

### ISSUE THREAD

**Issue by switzersc** [codefordenver/codeacross-2016#5]
### Recruit Participants

Once you have an agenda, it’s time to Recruit! Recruit! Recruit! People can get pretty busy and people can get even busier during the summer. In order to get people to your event you’ll need to start early. You can use your local organization’s email lists, social media accounts, contacts with local universities, companies, and news media to help spread the word.

The other things you’ll want to make sure of is that you recruit a diverse pool of participants. Reaching out to groups like the Chicago Women in Developers can be super-useful in doing this.

Additionally, you’ll also want to make sure you have a diverse skill set at your event.

The best teams at hackathons are comprised of a mix of skillsets including developers, user interface designers, data scientists, and subject matter experts.

There are a few strategies you can use to try to get a diverse group of people to your event including reaching out to Meetup groups (like other developer groups), contacting web development schools like DevBootcamp, and talking to local universities.

There’s a few ways that you can do registration for the event. For our groups, we like to use Meetup since it allows us to host discussions on the event page. It also help to carry the movement on afterwards since you’ll have people joining your meetup group when they register for the event.
- [ ] Reach out to tech meetups
- [ ] Reach out to art/design/other meetups
- [x] Email CfD meetup members
- [ ] Reach out to non-tech community groups
- [ ] Reach out to code schools
- [ ] Put flyers in relevant locations
- [ ] Reach out to universities

**Comment by karenderrickdavis** [comment]
confirmation from Manual High School that several students will come.

**Comment by karenderrickdavis** [comment]
Outreach copy:

We are excited to announce this year's CodeAcross on March 5, 2016 at the Commons on Champa. Last year's event was a huge success, bringing together new folks and seasoned members of Code for Denver to learn together and address community issues. This year we're looking forward to continuing this momentum with a similar focus on collaboration and community-building, but with new projects and activities.

The morning will feature an engaging design and empathy workshop developed by Stanford's D-School and led by expert facilitators from Denver and Boulder. Come prepared to have fun and learn a ton, with absolutely no previous tech or design skills needed.

The afternoon will be split into two tracks. The first will be an Intro to Code workshop led by pro instructors from RefactorU. This begins at 1pm and afterwards, participants are encouraged to join the second track and begin using their newly acquired skills.

The second afternoon track, 1pm-5pm, will be the Open Data Art/Code Challenge. Participants will form teams (or go solo - that's fine) and dive into datasets from the community, with the goal of finding innovative approaches to using and visualizing open data. At the end of the day, teams will have created artistic or digital (or both!) prototypes to visualize the data they worked with (e.g. infographics), interpret that data or an insight they gained from it (e.g. paintings), or allow users to interact with the data (e.g. web or mobile apps). The ideas and prototypes that emerge may become future projects to be worked on with Code for Denver, or even turned into public art projects in the city. More details to be announced.

We have a full schedule as well as parking information posted at our event meetup page. Please RSVP there so we can plan for food (breakfast and lunch will be provided): http://www.meetup.com/CodeForDenver/events/228539039/

Looking forward to seeing y'all there!
